language: php
os: linux
dist: bionic
sudo: false
php:
  - 7.2
  - 7.3
  - 7.4
after_success:
  - test -z $COVERALLS || (composer require php-coveralls/php-coveralls && vendor/bin/coveralls -v)
matrix:
  include:
    - php: 7.2
      env: COVERALLS=true
